defaults: &defaults
  title: "Tire Service"
  vat: 20
  currency: $
  company_name: "LTD Tire Service"
  iban: "ААВВ ССС DDDD ЕЕЕЕ ЕЕЕЕ ЕЕЕЕ ЕЕЕЕ"
  payer_account_number: 156212314

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
