export_i18n_js: false
translations:
  - file: app/javascript/front/common/translations.js
    only:
      - en.front.*
      - en.activerecord.*
      - en.time.*
      - ru.front.*
      - ru.activerecord.*
      - ru.errors.*
      - ru.helpers.*
      - ru.time.*
      - ru.date.*
  - file: app/javascript/admin/common/translations.js
    only:
      - en.admin.*
      - en.activerecord.*
      - ru.cocoon.*
      - ru.simple_form.*
      - ru.visit.*
      - ru.presentation.*
      - ru.activerecord.*
      - ru.errors.*
      - ru.admin.*
      - ru.colors.*
      - ru.ratesets.*
