#require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - lib/tasks/deployment/*
    - bin/**/*

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
  ExcludedMethods:
    - included

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Style/AsciiComments:
  Description: "Use only ascii symbols in comments."
  StyleGuide: "#english-comments"
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile

Style/Send:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": "[]"
    "%I": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"

Metrics/MethodLength:
  ExcludedMethods:
    - row_data
    - query
    - searched_by
    - form_controls

Metrics/CyclomaticComplexity:
  Max: 7

Naming/RescuedExceptionsVariableName:
  PreferredName: exception
