source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.3"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 5.2.4", ">= 5.2.4.5"
gem "rack", "~> 2.2.2"

# Observability
gem "yabeda", "~> 0.8.0"
gem "yabeda-rails", "~> 0.7.0"
gem "yabeda-prometheus-mmap", "~> 0.1.1"
gem "yabeda-puma-plugin", "~> 0.4.0"

# Lograge
gem "lograge", "~> 0.11.2"

# Web Server
gem "puma", "~> 3.11"
gem "paranoia", "~> 2.4", ">= 2.4.2"
gem "request_store", "~> 1.1.0"

# Configuration
gem "dotenv-rails"

# Database
gem "activeresource", "~> 5.1"
gem "pg", "~> 0.18.2"
gem "pg_search"
gem "redis", "~> 4.1", ">= 4.1.3"
gem "redis-namespace", "~> 1.7"
gem "seedbank", "~> 0.3.0"
gem "strong_migrations", "~> 0.6.4"
gem "activerecord-postgres_enum", "~> 1.6"
gem "pg_inheritance"
gem "groupdate"

# Authorization
gem "cancancan", "~> 1.15.0"
gem "devise", "~> 4.6.2"

# Backend plugins
gem "enumerize", "~> 2.3.1"
gem "rails_select_on_includes", "~> 5.2.1"

# Assets
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "mini_racer"
gem "font-awesome-rails", "~> 4.7", ">= 4.7.0.5"
gem "i18n-js", "~> 3.0.0.rc13"
gem "jquery-rails", "~> 4.1.1"
gem "sassc-rails"
gem "bootstrap", "~> 4.6.0"
gem "jquery-ui-rails"
gem "bootstrap_icons_rails"
gem "bootstrap-select-rails"
gem "chosen-rails"

# Front JS Rendering
gem "react-rails"
gem "webpacker", "~> 6.x"

# Views
gem "cocoon"
gem "simple-navigation", "~> 4.0.3"
gem "simple_form", "~> 4.1"
gem "slim-rails", "~> 3.1.1"
gem "chartkick"

# Serializators
gem "fast_jsonapi", "~> 1.5"

# Parser
gem "json-schema"
gem "nokogiri"
gem "fast_excel"

# API documentation
gem "rswag-api", "~> 2.2.0"
gem "rswag-ui", "~> 2.2.0"

# Validators
gem "activerecord_json_validator"
gem "validate_url"
gem "validates_timeliness"

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem "turbolinks", "~> 5"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.5"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.1.0", require: false

group :development, :test do
  gem "rspec-rails", "~> 3.9"

  gem "ffaker", "~> 2.17.0"

  # Preloader
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "spring-commands-rspec", "~> 1.0", ">= 1.0.4"

  # API documentation
  gem "rswag-specs", "~> 2.2.0"
end

group :development do
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "awesome_print"

  gem "web-console", ">= 3.3.0"
  gem "listen", ">= 3.0.5", "< 3.2"
end

group :test do
  gem "database_cleaner", "~> 1.7"
  gem "factory_bot_rails", "~> 5.1.1", require: false
  gem "json_matchers"
  gem "rails-controller-testing", "~> 1.0", ">= 1.0.4"
  gem "shoulda-matchers", "~> 4.1.2"
  gem "timecop", "~> 0.9.1"
  gem "webmock", "~> 3.5", ">= 3.5.1"
  gem "timecop-rspec", "~> 1.0.0", git: "https://github.com/avantoss/timecop-rspec"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
