source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.6"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 5.2.4", ">= 5.2.4.5"
gem "rack", "~> 2.2.2"

# Web Server
gem "puma", "~> 3.11"

# Configuration
gem "dotenv-rails"

# Database
gem "activeresource", "~> 5.1"
gem "pg", "~> 0.18.2"
gem "pg_search", "~> 1.0.3"
gem "redis", "~> 4.1", ">= 4.1.3"
gem "redis-namespace", "~> 1.7"
gem "seedbank", "~> 0.3.0"
gem "strong_migrations", "~> 0.6.4"
gem "activerecord-postgres_enum", "~> 1.6"

# Authorization
gem "cancancan", "~> 1.15.0"
gem "devise", "~> 4.6.2"

# Backend plugins
gem "enumerize", "~> 2.3.1"
gem "rails_select_on_includes", "~> 5.2.1"

# Assets
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "mini_racer"
gem "font-awesome-rails", "~> 4.7", ">= 4.7.0.5"
gem "i18n-js", "~> 3.0.0.rc13"
gem "jquery-rails", "~> 4.1.1"

# Serializators
gem "fast_jsonapi", "~> 1.5"

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem "turbolinks", "~> 5"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.5"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.1.0", require: false

group :development, :test do
  gem "rspec-rails", "~> 3.9"
  # Preloader
  gem "spring", "~> 2.0", ">= 2.0.2"
  gem "spring-commands-rspec", "~> 1.0", ">= 1.0.4"
end

group :development do
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "awesome_print"

  gem "web-console", ">= 3.3.0"
  gem "listen", ">= 3.0.5", "< 3.2"
end

group :test do
  gem "database_cleaner", "~> 1.7"
  gem "factory_bot_rails", "~> 5.1.1", require: false
  gem "ffaker", "~> 2.13.0"
  gem "json_matchers", "~> 0.11.0"
  gem "rails-controller-testing", "~> 1.0", ">= 1.0.4"
  gem "shoulda-matchers", "~> 4.1.2"
  gem "webmock", "~> 3.5", ">= 3.5.1"
end
